compile :
	md5sum -c --quiet check
	gcc q02_01.c academic.c custom.c -o q02_01
	gcc q02_02.c academic.c custom.c -o q02_02
	gcc q02_03.c academic.c custom.c -o q02_03
	gcc q02_04.c academic.c custom.c -o q02_04

test_01 :
	./q02_01

test_02 :
	./q02_02

test_03 :
	./q02_03

test_04 :
	./q02_04

test_05 :
	./q02_04
