compile :
	gcc t05_00.c academic.c -o t05_00
	gcc t05_01.c academic.c -o t05_01
	gcc t05_02.c academic.c -o t05_02
	gcc t05_03.c academic.c -o t05_03

test_00 :
	./t05_00

test_01 :
	./t05_01

test_02 :
	./t05_02

test_03 :
	./t05_03
