compile :
	gcc t06_01.c academic.c -o t06_01
	gcc t06_02.c academic.c -o t06_02
	gcc t06_03.c academic.c -o t06_03
	gcc t06_04.c academic.c -o t06_04
	gcc t06_05.c academic.c -o t06_05

test_01 :
	./t06_01

test_02 :
	./t06_02

test_03 :
	./t06_03

test_04 :
	./t06_04

test_05 :
	./t06_05
